freebsd_instance:
  image_family: freebsd-13-0-snap

task:
    install_script: pkg install -y cmake ninja freetype2 fontconfig pkgconf lcms2 nspr png tiff nss openjpeg cairo qt5-widgets qt5-xml qt5-qmake qt5-buildtools qt5-testlib qt6-base
    script: cmake . -G Ninja -DCMAKE_CXX_FLAGS="-Werror -Wno-deprecated-declarations" && ninja
