before_install:
  - eval "${MATRIX_EVAL}"
  - sudo add-apt-repository ppa:ricotz/testing -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenjpeg-dev qtbase5-dev gobject-introspection libglib2.0-dev

language: cpp

compiler:
 - clang
 - gcc

script: cmake . && make
