language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      before_install:
        - brew uninstall poppler gdal postgis python@2 mercurial
        - brew install poppler --only-dependencies --build-from-source
      script: cmake . -DFONT_CONFIGURATION=generic -DBUILD_SHARED_LIBS=OFF && make

    - os: osx
      osx_image: xcode11.2
      before_install:
        - brew uninstall poppler gdal postgis
        - brew install poppler --only-dependencies --build-from-source
      script: cmake . -DFONT_CONFIGURATION=generic -DBUILD_SHARED_LIBS=OFF && make

